//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engrande.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int TypeId { get; set; }
        public int UnitId { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual PriceType PriceType { get; set; }
        public virtual PriceUnit PriceUnit { get; set; }
    }
}
